### ISSUE TITLE
テストも書いてみてください

### ISSUE THREAD

**Issue by mosson** [hajime-takubo/FizzbuzzTest#1]

**Comment by mosson** [comment]
- マイルストーンを作ってください
- テストを書くというissueをマイルストーンと関連づけて発行してください
- 実際にテストコードをかいて`refs`をつかって該当issueとcommitをひもづけてください

**Comment by hajime-takubo** [comment]
上記を試してみました。

**Comment by mosson** [comment]
確認しました

**Comment by hajime-takubo** [comment]
ご確認ありがとうございます
