### ISSUE TITLE
テストを書く

### ISSUE THREAD

**Issue by hajime-takubo** [hajime-takubo/FizzbuzzTest#2]
●Fizzbuzzのテストコードを書く

●refsをつかって該当issueとcommitを紐づける

**Comment by mosson** [comment]
確認しました。
コミットメッセージがわかりづらいです。

`#2 テストを追加した`
`不要なファイルを削除した`

など何をしたのかわかるようにしてください

**Comment by hajime-takubo** [comment]
ご指摘ありがとうございます。
了解いたしました。以後気をつけます。
