### ISSUE TITLE
README.mdを追加してください。

### ISSUE THREAD

**Issue by mosson** [hajime-takubo/FizzbuzzTest#7]
何のためのリポジトリなのか
どういったコマンドをうつと何がおきるのか

**Comment by hajime-takubo** [comment]
了解いたしました。

**Comment by mosson** [comment]
マークダウンの書式で
\` (バッククォート) \` でくくると `inline code goes` のような出力に、
\`\`\` (バッククォート三つ) \`\`\` でくくると

```
// code

// goes

// here
```

のような出力にできます

**Comment by mosson** [comment]
シェルのコマンドはコードブロックにしたほうが読みやすいです。
また先頭に`$`をつけた方がよりシェルだということがわかります。

```
$ bundle exec rake:some
```

**Comment by hajime-takubo** [comment]
情報とご指摘、ありがとうございます。

**Comment by mosson** [comment]
そもそもFizzBuzzの説明がないです

**Comment by hajime-takubo** [comment]
すみません、追記します。

**Comment by hajime-takubo** [comment]
FizzBuzzの説明を追記しました。

**Comment by mosson** [comment]
改行とコードブロックの使用に気をつけて見直してください

**Comment by hajime-takubo** [comment]
了解いたしました。

**Comment by hajime-takubo** [comment]
確認が不足していて申し訳ありませんでした。
README.mdを修正いたしました

**Comment by mosson** [comment]
確認しました。closeとします。

余談ですが謝る必要は全くない、というか謝られるとやりずらいのであんまりかしこまらないでください。

**Comment by hajime-takubo** [comment]
はい(^^)
